/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema;

import java.sql.*; // importar todas las librerias de sql 
import conexionDB.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author mathiasvenegas
 */
public class facturacion extends javax.swing.JFrame {

    Conexion conect = new Conexion();
    Connection conectar = conect.getConnection();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(facturacion.class.getName());

    /**
     * Creates new form facturacion
     */
    public facturacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtCantidadGraderiaSol.setEditable(false);
        txtCantidadGraderiaSombra.setEditable(false);
        txtCantidadPalco.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidoCliente = new javax.swing.JTextField();
        txtCedulaCliente = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnVenta = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCantidadGraderiaSol = new javax.swing.JTextField();
        rbGraderiaSol = new javax.swing.JRadioButton();
        rbGraderiaSombra = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbPalcoPreferencial = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCantidadGraderiaSombra = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCantidadPalco = new javax.swing.JTextField();
        txtSalir = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Sistema de facturacion del Estadio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Nombre del cliente:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Apellido del cliente:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Cedula del cliente:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setText("Total:");

        txtApellidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoClienteActionPerformed(evt);
            }
        });

        txtTotal.setEditable(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        btnVenta.setText("Realizar Venta");
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setText("Cantidad:");

        txtCantidadGraderiaSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadGraderiaSolActionPerformed(evt);
            }
        });

        rbGraderiaSol.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        rbGraderiaSol.setText("Entrada a Graderia Sol");
        rbGraderiaSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGraderiaSolActionPerformed(evt);
            }
        });

        rbGraderiaSombra.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        rbGraderiaSombra.setText("Entrada a Graderia Sombra");
        rbGraderiaSombra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGraderiaSombraActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("...................... ₡6000");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel8.setText("................ ₡9000");

        rbPalcoPreferencial.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        rbPalcoPreferencial.setText("Entrada a Palco Preferencial");
        rbPalcoPreferencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPalcoPreferencialActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setText("............ ₡25000");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel10.setText("LOS PRECIOS NO TIENEN EL IVA ");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel11.setText("Subtotal:");

        txtSubtotal.setEditable(false);
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel12.setText("Cantidad:");

        txtCantidadGraderiaSombra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadGraderiaSombraActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel13.setText("Cantidad:");

        txtSalir.setText("SALIR");
        txtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalirActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(rbGraderiaSol)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel7)
                                    .addGap(12, 12, 12))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(rbGraderiaSombra)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(rbPalcoPreferencial)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel9)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCantidadGraderiaSol, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCantidadGraderiaSombra, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(txtCantidadPalco, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGap(28, 28, 28))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(183, 183, 183)
                            .addComponent(btnVenta)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(22, 22, 22))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(txtApellidoCliente)
                                    .addComponent(txtCedulaCliente))
                                .addGap(129, 129, 129))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnLimpiar)
                                .addComponent(btnCalcular))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnVolver)
                                    .addComponent(txtSalir))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSalir)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnVolver)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbGraderiaSol)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(txtCantidadGraderiaSol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbGraderiaSombra)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(txtCantidadGraderiaSombra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPalcoPreferencial)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(txtCantidadPalco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10)
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCalcular)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVenta)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoClienteActionPerformed

    private void rbGraderiaSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGraderiaSolActionPerformed
        // TODO add your handling code here:
        txtCantidadGraderiaSol.setEditable(true);
    }//GEN-LAST:event_rbGraderiaSolActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        Calcular();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void rbGraderiaSombraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGraderiaSombraActionPerformed
        // TODO add your handling code here:
        txtCantidadGraderiaSombra.setEditable(true);
    }//GEN-LAST:event_rbGraderiaSombraActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void txtCantidadGraderiaSombraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadGraderiaSombraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadGraderiaSombraActionPerformed

    private void txtCantidadGraderiaSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadGraderiaSolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadGraderiaSolActionPerformed

    private void rbPalcoPreferencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPalcoPreferencialActionPerformed
        // TODO add your handling code here:
        txtCantidadPalco.setEditable(true);
    }//GEN-LAST:event_rbPalcoPreferencialActionPerformed

    private void txtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txtSalirActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        // TODO add your handling code here:
        Calcular();
        venta();
        Limpiar();
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        login abrir = new login();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    public void Limpiar() {
        txtNombreCliente.setText("");
        txtApellidoCliente.setText("");
        txtCedulaCliente.setText("");
        rbGraderiaSol.setSelected(false);
        rbGraderiaSombra.setSelected(false);
        rbPalcoPreferencial.setSelected(false);
        txtCantidadGraderiaSol.setText("");
        txtCantidadGraderiaSombra.setText("");
        txtCantidadPalco.setText("");
        txtSubtotal.setText("");
        txtTotal.setText("");
    }

    public void Calcular() {
        final int GRADERIA_SOL = 6000, GRADERIA_SOMBRA = 9000, PALCO_PREFERENCIAL = 25000;
        final double IVA = 0.13;

        String cantidad1Str = txtCantidadGraderiaSol.getText().trim();
        String cantidad2Str = txtCantidadGraderiaSombra.getText().trim();
        String cantidad3Str = txtCantidadPalco.getText().trim();

        try {

            int cantidad1 = cantidad1Str.isEmpty() ? 0 : Integer.parseInt(cantidad1Str);
            int cantidad2 = cantidad2Str.isEmpty() ? 0 : Integer.parseInt(cantidad2Str);
            int cantidad3 = cantidad3Str.isEmpty() ? 0 : Integer.parseInt(cantidad3Str);

            double subtotal1 = GRADERIA_SOL * cantidad1;
            double subtotal2 = GRADERIA_SOMBRA * cantidad2;
            double subtotal3 = PALCO_PREFERENCIAL * cantidad3;

            double subtotalTotal = subtotal1 + subtotal2 + subtotal3;

            double total = subtotalTotal + (subtotalTotal * IVA);

            String subtotalFormateado = String.format("₡%.2f", subtotalTotal);
            txtSubtotal.setText(subtotalFormateado);

            String totalFormateado = String.format("₡%.2f", total);
            txtTotal.setText(totalFormateado);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese solo números válidos",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void venta() {
    final int PRECIO_SOL = 6000;
    final int PRECIO_SOMBRA = 9000;
    final int PRECIO_PALCO = 25000;
    
    
    String nombre = txtNombreCliente.getText().trim();
    String apellido = txtApellidoCliente.getText().trim();
    String cedula = txtCedulaCliente.getText().trim();
    String cantidadSolStr = txtCantidadGraderiaSol.getText().trim();
    String cantidadSombraStr = txtCantidadGraderiaSombra.getText().trim();
    String cantidadPalcoStr = txtCantidadPalco.getText().trim();
    String subtotalStr = txtSubtotal.getText().trim();
    String totalStr = txtTotal.getText().trim();  
    
    try {
       
        int cantidadSol = cantidadSolStr.isEmpty() ? 0 : Integer.parseInt(cantidadSolStr);
        int cantidadSombra = cantidadSombraStr.isEmpty() ? 0 : Integer.parseInt(cantidadSombraStr);
        int cantidadPalco = cantidadPalcoStr.isEmpty() ? 0 : Integer.parseInt(cantidadPalcoStr);
        
        
        subtotalStr = subtotalStr.replace("₡", "").replace(",", "").trim();
        totalStr = totalStr.replace("₡", "").replace(",", "").trim();
        
        double subtotal = Double.parseDouble(subtotalStr);
        double total = Double.parseDouble(totalStr);
        
        // Guardar en la base de datos
        Conexion conect = new Conexion();
        Connection conectar = conect.getConnection();
        
        String sql = "INSERT INTO facturacion (nombreCliente, apellidoCliente, cedulaCliente, "
                + "graderiaSol, graderiaSombra, palco, subtotal, total) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        
        PreparedStatement pst = conectar.prepareStatement(sql);
        pst.setString(1, nombre);
        pst.setString(2, apellido);
        pst.setString(3, cedula);
        pst.setInt(4, cantidadSol);
        pst.setInt(5, cantidadSombra);
        pst.setInt(6, cantidadPalco);
        pst.setDouble(7, subtotal);
        pst.setDouble(8, total);
        
        int resultado = pst.executeUpdate();
        
        if (resultado > 0) {
            String factura = "";
            factura += "═══════════════════════════════════════\n";
            factura += "          FACTURA DE VENTA\n";
            factura += "═══════════════════════════════════════\n\n";
            factura += "DATOS DEL CLIENTE:\n";
            factura += "───────────────────────────────────────\n";
            factura += "Nombre: " + nombre + " " + apellido + "\n";
            factura += "Cédula: " + cedula + "\n\n";
            factura += "DETALLE DE COMPRA:\n";
            factura += "───────────────────────────────────────\n";
            
            if (cantidadSol > 0) {
                factura += String.format("Gradería Sol       x%d  ₡%,d\n",
                        cantidadSol, PRECIO_SOL * cantidadSol);
            }
            if (cantidadSombra > 0) {
                factura += String.format("Gradería Sombra    x%d  ₡%,d\n",
                        cantidadSombra, PRECIO_SOMBRA * cantidadSombra);
            }
            if (cantidadPalco > 0) {
                factura += String.format("Palco Preferencial x%d  ₡%,d\n",
                        cantidadPalco, PRECIO_PALCO * cantidadPalco);
            }
            
            factura += "\n───────────────────────────────────────\n";
            factura += String.format("Subtotal:                   ₡%,.2f\n", subtotal);
            factura += String.format("IVA (13%%):                  ₡%,.2f\n", (total - subtotal));
            factura += "═══════════════════════════════════════\n";
            factura += String.format("TOTAL:                      ₡%,.2f\n", total);
            factura += "═══════════════════════════════════════\n\n";
            factura += "       ¡Gracias por su compra!\n";
            
            JOptionPane.showMessageDialog(this, factura,
                    "FACTURA - Venta Exitosa",
                    JOptionPane.INFORMATION_MESSAGE);
            

            Limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar la venta",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        pst.close();
        conectar.close();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "ERROR:" + e);
    }
}
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new facturacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVenta;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbGraderiaSol;
    private javax.swing.JRadioButton rbGraderiaSombra;
    private javax.swing.JRadioButton rbPalcoPreferencial;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JTextField txtCantidadGraderiaSol;
    private javax.swing.JTextField txtCantidadGraderiaSombra;
    private javax.swing.JTextField txtCantidadPalco;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JButton txtSalir;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
